services:
  - type: web
    name: codveda-internship-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb://localhost:27017/codveda
      - key: JWT_SECRET
        value: codveda_internship_secret_key_2024

